repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you want to point at
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=51200']
    -   id: debug-statements

-   repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        # language_version: python3.6


-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
        entry: bash -c 'flake8 "$@" || true' --
        verbose: true

-   repo: https://github.com/PyCQA/pylint
    rev: v2.8.2
    hooks:
    -   id: pylint
        entry: bash -c 'pylint "$@" || true' --
        verbose: true

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        entry: bash -c 'bandit "$@" || true' --

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.812
#     hooks:
#     -   id: mypy
#         # args: [--strict]
#         # args: [--no-strict-optional, --ignore-missing-imports]


